insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(1,'BLG','01','BG41','Благоевград','04279','Blaevgrad',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(2,'BGS','02','BG34','Бургас','07079','Burgas',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(3,'VAR','03','BG33','Варна','10135','Varna',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(4,'VTR','04','BG32','Велико Търново','10447','Veliko Tarnovo',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(5,'VID','05','BG31','Видин','10971','Vidin',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(6,'VRC','06','BG31','Враца','12259','Vratsa',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(7,'GAB','07','BG32','Габрово','14218','Gabrovo',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(8,'DOB','08','BG33','Добрич','72624','Dobrich',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(9,'KRZ','09','BG42','Кърджали','40909','Kardzhali',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(10,'KNL','10','BG41','Кюстендил','41112','Kyustendil',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(11,'LOV','11','BG31','Ловеч','43952','Lovech',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(12,'MON','12','BG31','Монтана','48489','Montana',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(13,'PAZ','13','BG42','Пазарджик','55155','Pazardzhik',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(14,'PER','14','BG41','Перник','55871','Pernik',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(15,'PVN','15','BG31','Плевен','56722','Pleven',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(16,'PDV','16','BG42','Пловдив','56784','Plovdiv',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(17,'RAZ','17','BG32','Разград','61710','Razgrad',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(18,'RSE','18','BG32','Русе','63427','Ruse',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(19,'SLS','19','BG32','Силистра','66425','Silistra',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(20,'SLV','20','BG34','Сливен','67338','Sliven',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(21,'SML','21','BG42','Смолян','67653','Smolyan',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(22,'SOF','22','BG41','София (столица)','68134','Sofia (capital)',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(23,'SFO','23','BG41','София','68134','Sofia',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(24,'SZR','24','BG34','Стара Загора','68850','Stara Zara',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(25,'TGV','25','BG33','Търговище','73626','Tarvishte',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(26,'HKV','26','BG42','Хасково','77195','Haskovo',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(27,'SHU','27','BG33','Шумен','83510','Shumen',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(28,'JAM','28','BG34','Ямбол','87374','Yambol',true,0);
insert into district(id, code, code2, secondlevelregioncode, name, mainsettlementcode, namealt, isactive, version) values(29,'MISSING','null', null,'Липсва', null,'Missing',false,0);