insert into ministryofinterior (isactive, name, vieworder) values (true, 'Столична дирекция на вътрешните работи', 1);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Благоевград', 2);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Бургас', 3);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Варна', 4);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Велико Търново', 5);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Видин', 6);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Враца', 7);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Габрово', 8);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Добрич', 9);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Кърджали', 10);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Кюстендил', 11);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Ловеч', 12);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Монтана', 13);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Пазарджик', 14);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Перник', 15);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Плевен', 16);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Пловдив', 17);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Разград', 18);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Русе', 19);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Силистра', 20);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Сливен', 21);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Смолян', 22);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - София', 23);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Стара Загора', 24);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Търговище', 25);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Хасково', 26);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Шумен', 27);
insert into ministryofinterior (isactive, name, vieworder) values (true, 'ОДМВР - Ямбол', 28);