insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (1, true, 'Върховен административен съд', 1);

insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Благоевград', 2);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Бургас', 3);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Варна', 4);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Велико Търново', 5);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Видин', 6);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Враца', 7);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Габрово', 8);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Добрич', 9);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Кърджали', 10);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Кюстендил', 11);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Ловеч', 12);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Монтана', 13);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Пазарджик', 14);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Перник', 15);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Плевен', 16);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Пловдив', 17);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Разград', 18);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Русе', 19);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Силистра', 20);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Сливен', 21);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Смолян', 22);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - София-град', 23);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - София-област', 24);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Стара Загора', 25);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Търговище', 26);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Хасково', 27);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Шумен', 28);
insert into administrativecourt (administrativecourttype, isactive, name, vieworder) values (2, true, 'Административен съд - Ямбол', 29);