insert into code (isactive, name) values (true, '01.11 Отглеждане на зърнени (без ориз) и бобови растения и маслодайни семена');
insert into code (isactive, name) values (true, '01.12 Отглеждане на ориз');
insert into code (isactive, name) values (true, '01.13 Отглеждане на зеленчуци, дини и пъпеши, кореноплодни и грудкови');
insert into code (isactive, name) values (true, '01.14 Отглеждане на захарна тръстика');
insert into code (isactive, name) values (true, '01.15 Отглеждане на тютюн');
insert into code (isactive, name) values (true, '01.16 Отглеждане на влакнодайни растения');
insert into code (isactive, name) values (true, '01.19 Отглеждане на други едногодишни растения');
insert into code (isactive, name) values (true, '01.21 Отглеждане на грозде');
insert into code (isactive, name) values (true, '01.22 Отглеждане на тропични и субтропични плодове');
insert into code (isactive, name) values (true, '01.23 Отглеждане на цитрусови плодове');
insert into code (isactive, name) values (true, '01.24 Отглеждане на семкови и костилкови плодове');
insert into code (isactive, name) values (true, '01.25 Отглеждане на черупкови, ягодоплодни и други плодове');
insert into code (isactive, name) values (true, '01.26 Отглеждане на маслосъдържащи плодове');
insert into code (isactive, name) values (true, '01.27 Отглеждане на растения за напитки');
insert into code (isactive, name) values (true, '01.28 Отглеждане на подправки, етеричномаслени и лечебни растения');
insert into code (isactive, name) values (true, '01.29 Отглеждане на други многогодишни насаждения');
insert into code (isactive, name) values (true, '01.30 Дейности на разсадници, без горските');
insert into code (isactive, name) values (true, '01.41 Отглеждане на едър рогат добитък, с млечно направление');
insert into code (isactive, name) values (true, '01.42 Отглеждане на едър рогат добитък, с друго направление');
insert into code (isactive, name) values (true, '01.43 Отглеждане на коне, магарета, мулета и катъри');
insert into code (isactive, name) values (true, '01.44 Отглеждане на камили, лами и подобни животни');
insert into code (isactive, name) values (true, '01.45 Отглеждане на дребен рогат добитък');
insert into code (isactive, name) values (true, '01.46 Отглеждане на свине');
insert into code (isactive, name) values (true, '01.47 Отглеждане на домашни птици');
insert into code (isactive, name) values (true, '01.49 Отглеждане на други животни');
insert into code (isactive, name) values (true, '01.50 Комбинирано растениевъдно-животновъдно стопанство');
insert into code (isactive, name) values (true, '01.61 Спомагателни дейности в растениевъдството');
insert into code (isactive, name) values (true, '01.62 Спомагателни дейности в животновъдството');
insert into code (isactive, name) values (true, '01.63 Дейности след прибиране на реколтата');
insert into code (isactive, name) values (true, '01.64 Обработка на семена за посев');
insert into code (isactive, name) values (true, '01.70 Лов и спомагателни дейности');
insert into code (isactive, name) values (true, '02.10 Възпроизводство на гори');
insert into code (isactive, name) values (true, '02.20 Дърводобив');
insert into code (isactive, name) values (true, '02.30 Събиране на диворастящи и недървесни продукти');
insert into code (isactive, name) values (true, '02.40 Спомагателни дейности в горското стопанство');
insert into code (isactive, name) values (true, '03.11 Океански и морски риболов');
insert into code (isactive, name) values (true, '03.12 Сладководен риболов');
insert into code (isactive, name) values (true, '03.21 Развъждане и отглеждане на риба и други водни организми в солени басейни');
insert into code (isactive, name) values (true, '03.22 Развъждане и отглеждане на риба и други водни организми в сладководни басейни');
insert into code (isactive, name) values (true, '05.10 Добив на антрацитни и черни въглища');
insert into code (isactive, name) values (true, '05.20 Добив на кафяви и лигнитни въглища');
insert into code (isactive, name) values (true, '06.10 Добив на нефт');
insert into code (isactive, name) values (true, '06.20 Добив на природен газ');
insert into code (isactive, name) values (true, '07.10 Добив на железни руди');
insert into code (isactive, name) values (true, '07.21 Добив на уранови и ториеви руди');
insert into code (isactive, name) values (true, '07.29 Добив на руди на цветни метали');
insert into code (isactive, name) values (true, '08.11 Добив на строителни и декоративни скални материали, варовик, суров гипс, креда, доломит и шисти');
insert into code (isactive, name) values (true, '08.12 Добив на трошен камък, чакъл и пясък; добив на глина и каолин');
insert into code (isactive, name) values (true, '08.91 Добив на минерални суровини за химическото производство и на естествени торове');
insert into code (isactive, name) values (true, '08.92 Добив на торф');
insert into code (isactive, name) values (true, '08.93 Добив на сол');
insert into code (isactive, name) values (true, '08.99 Добив на други неметални материали и суровини, некласифицирани другаде');
insert into code (isactive, name) values (true, '09.10 Спомагателни дейности в добива на нефт и природен газ');
insert into code (isactive, name) values (true, '09.90 Спомагателни дейности в добива, без добива на нефт и природен газ');
insert into code (isactive, name) values (true, '10.11 Производство и преработка на месо, без месо от домашни птици');
insert into code (isactive, name) values (true, '10.12 Производство и преработка на месо от домашни птици');
insert into code (isactive, name) values (true, '10.13 Производство на месни продукти, без готови ястия');
insert into code (isactive, name) values (true, '10.20 Преработка и консервиране на риба и други водни животни, без готови ястия');
insert into code (isactive, name) values (true, '10.31 Преработка и консервиране на картофи');
insert into code (isactive, name) values (true, '10.32 Производство на плодови и зеленчукови сокове');
insert into code (isactive, name) values (true, '10.39 Преработка и консервиране на други плодове и зеленчуци, без готови ястия');
insert into code (isactive, name) values (true, '10.41 Производство на растителни и животински масла и мазнини, без маргарин');
insert into code (isactive, name) values (true, '10.42 Производство на маргарин и подобни хранителни мазнини');
insert into code (isactive, name) values (true, '10.51 Производство на мляко и млечни продукти, без сладолед');
insert into code (isactive, name) values (true, '10.52 Производство на сладолед');
insert into code (isactive, name) values (true, '10.61 Производство на мелничарски продукти');
insert into code (isactive, name) values (true, '10.62 Производство на нишесте и нишестени продукти');
insert into code (isactive, name) values (true, '10.71 Производство на хляб, хлебни и пресни сладкарски изделия');
insert into code (isactive, name) values (true, '10.72 Производство на сухари, бисквити и сухи сладкарски изделия');
insert into code (isactive, name) values (true, '10.73 Производство на макарони, юфка, кускус и подобни макаронени изделия');
insert into code (isactive, name) values (true, '10.81 Производство на захар');
insert into code (isactive, name) values (true, '10.82 Производство на какао, шоколадови и захарни изделия');
insert into code (isactive, name) values (true, '10.83 Преработка на кафе и чай');
insert into code (isactive, name) values (true, '10.84 Производство на хранителни подправки и овкусители');
insert into code (isactive, name) values (true, '10.85 Производство на готови ястия');
insert into code (isactive, name) values (true, '10.86 Производство на детски, диетични и други хомогенизирани храни');
insert into code (isactive, name) values (true, '10.89 Производство на други хранителни продукти, некласифицирани другаде');
insert into code (isactive, name) values (true, '10.91 Производство на готови храни (фуражи) за селскостопански животни');
insert into code (isactive, name) values (true, '10.92 Производство на готови храни за домашни любимци');
insert into code (isactive, name) values (true, '11.01 Производство на спиртни напитки');
insert into code (isactive, name) values (true, '11.02 Производство на вина от грозде');
insert into code (isactive, name) values (true, '11.03 Производство на други ферментирали напитки');
insert into code (isactive, name) values (true, '11.04 Производство на други недестилирани алкохолни напитки');
insert into code (isactive, name) values (true, '11.05 Производство на пиво');
insert into code (isactive, name) values (true, '11.06 Производство на малц');
insert into code (isactive, name) values (true, '11.07 Производство на безалкохолни напитки, минерални и други бутилирани води');
insert into code (isactive, name) values (true, '12.00 Производство на тютюневи изделия');
insert into code (isactive, name) values (true, '13.10 Подготовка и предене на текстилни влакна');
insert into code (isactive, name) values (true, '13.20 Производство на тъкани');
insert into code (isactive, name) values (true, '13.30 Облагородяване на прежди, платове и облекло');
insert into code (isactive, name) values (true, '13.91 Производство на плетени платове');
insert into code (isactive, name) values (true, '13.92 Производство на конфекционирани текстилни изделия, без облекло');
insert into code (isactive, name) values (true, '13.93 Производство на килими и текстилни подови настилки');
insert into code (isactive, name) values (true, '13.94 Производство на канапи, въжета, мрежи и изделия от тях');
insert into code (isactive, name) values (true, '13.95 Производство на нетъкани текстилни изделия, без облекло');
insert into code (isactive, name) values (true, '13.96 Производство на други текстилни изделия за техническа и производствена употреба');
insert into code (isactive, name) values (true, '13.99 Производство на други текстилни изделия, некласифицирани другаде');
insert into code (isactive, name) values (true, '14.11 Производство на облекло от обработени меки кожи');
insert into code (isactive, name) values (true, '14.12 Производство на работно облекло');
insert into code (isactive, name) values (true, '14.13 Производство на горно облекло, без работно');
insert into code (isactive, name) values (true, '14.14 Производство на долно облекло');
insert into code (isactive, name) values (true, '14.19 Производство на друго облекло и допълнения за облекло');
insert into code (isactive, name) values (true, '14.20 Производство на облекло и изделия от кожухарски кожи');
insert into code (isactive, name) values (true, '14.31 Производство на чорапи и чорапогащи');
insert into code (isactive, name) values (true, '14.39 Производство на класически (машинно или ръчно плетени) пуловери, жилетки и други подобни изделия');
insert into code (isactive, name) values (true, '15.11 Обработка на кожи без косъм; обработка и багрене на кожухарски кожи');
insert into code (isactive, name) values (true, '15.12 Производство на куфари, чанти и други изделия за пътуване, сарашки и седларски изделия');
insert into code (isactive, name) values (true, '15.20 Производство на обувки');
insert into code (isactive, name) values (true, '16.10 Разкрояване, рендосване и импрегниране на дървен материал');
insert into code (isactive, name) values (true, '16.21 Производство на фурнир и дървесни плочи');
insert into code (isactive, name) values (true, '16.22 Производство на сглобени паркетни плочи');
insert into code (isactive, name) values (true, '16.23 Производство на дограма и други изделия от дървен материал за строителството');
insert into code (isactive, name) values (true, '16.24 Производство на опаковки от дървен материал');
insert into code (isactive, name) values (true, '16.29 Производство на други изделия от дървен материал; производство на изделия от корк, слама и материали за плетене');
insert into code (isactive, name) values (true, '17.11 Производство на влакнести полуфабрикати');
insert into code (isactive, name) values (true, '17.12 Производство на хартия и картон');
insert into code (isactive, name) values (true, '17.21 Производство на вълнообразен картон и опаковки от хартия и картон');
insert into code (isactive, name) values (true, '17.22 Производство на домакински, санитарно-хигиенни и тоалетни изделия от хартия и картон');
insert into code (isactive, name) values (true, '17.23 Производство на канцеларски материали от хартия и картон');
insert into code (isactive, name) values (true, '17.24 Производство на тапети и подобни стенни облицовки');
insert into code (isactive, name) values (true, '17.29 Производство на други изделия от хартия и картон');
insert into code (isactive, name) values (true, '18.11 Печатане на вестници');
insert into code (isactive, name) values (true, '18.12 Печатане на други издания и печатни продукти');
insert into code (isactive, name) values (true, '18.13 Предпечатна подготовка');
insert into code (isactive, name) values (true, '18.14 Подвързване и подобни дейности, свързани с печатането');
insert into code (isactive, name) values (true, '18.20 Възпроизвеждане на записани носители');
insert into code (isactive, name) values (true, '19.10 Производство на кокс и продукти на коксуването');
insert into code (isactive, name) values (true, '19.20 Производство на рафинирани нефтопродукти и брикети от въглища и торф');
insert into code (isactive, name) values (true, '20.11 Производство на промишлени газове');
insert into code (isactive, name) values (true, '20.12 Производство на багрила и пигменти');
insert into code (isactive, name) values (true, '20.13 Производство на други основни неорганични химични вещества');
insert into code (isactive, name) values (true, '20.14 Производство на други основни органични химични вещества');
insert into code (isactive, name) values (true, '20.15 Производство на азотни съединения и торове');
insert into code (isactive, name) values (true, '20.16 Производство на полимери в първични форми');
insert into code (isactive, name) values (true, '20.17 Производство на синтетичен каучук в първични форми');
insert into code (isactive, name) values (true, '20.20 Производство на пестициди и други агрохимикали');
insert into code (isactive, name) values (true, '20.30 Производство на бои, лакове и подобни продукти, печатарско мастило и китове');
insert into code (isactive, name) values (true, '20.41 Производство на сапун, миещи, почистващи и полиращи препарати');
insert into code (isactive, name) values (true, '20.42 Производство на парфюми и тоалетни продукти');
insert into code (isactive, name) values (true, '20.51 Производство на експлозиви');
insert into code (isactive, name) values (true, '20.52 Производство на лепила');
insert into code (isactive, name) values (true, '20.53 Производство на етерични масла');
insert into code (isactive, name) values (true, '20.59 Производство на други химични продукти, некласифицирани другаде');
insert into code (isactive, name) values (true, '20.60 Производство на изкуствени и синтетични влакна');
insert into code (isactive, name) values (true, '21.10 Производство на лекарствени вещества');
insert into code (isactive, name) values (true, '21.20 Производство на лекарствени продукти');
insert into code (isactive, name) values (true, '22.11 Производство на външни и вътрешни гуми; регенериране на пневматични гуми');
insert into code (isactive, name) values (true, '22.19 Производство на други изделия от каучук');
insert into code (isactive, name) values (true, '22.21 Производство на листове, плочи, тръби и профили, от пластмаси');
insert into code (isactive, name) values (true, '22.22 Производство на опаковки от пластмаси');
insert into code (isactive, name) values (true, '22.23 Производство на дограма и други изделия от пластмаси за строителството');
insert into code (isactive, name) values (true, '22.29 Производство на други изделия от пластмаси');
insert into code (isactive, name) values (true, '23.11 Производство на необработено плоско стъкло');
insert into code (isactive, name) values (true, '23.12 Формуване и обработване на плоско стъкло');
insert into code (isactive, name) values (true, '23.13 Производство на опаковки и домакинско стъкло');
insert into code (isactive, name) values (true, '23.14 Производство на стъклени влакна');
insert into code (isactive, name) values (true, '23.19 Производство и обработване на други изделия от стъкло, вкл. за техническа употреба');
insert into code (isactive, name) values (true, '23.20 Производство на огнеупорни изделия');
insert into code (isactive, name) values (true, '23.31 Производство на керамични плочки');
insert into code (isactive, name) values (true, '23.32 Производство на тухли, керемиди и други изделия от печена глина за строителството');
insert into code (isactive, name) values (true, '23.41 Производство на домакински порцелан, декоративни изделия от порцелан и други керамични материали');
insert into code (isactive, name) values (true, '23.42 Производство на санитарна керамика');
insert into code (isactive, name) values (true, '23.43 Производство на керамични изолатори');
insert into code (isactive, name) values (true, '23.44 Производство на друга техническа керамика');
insert into code (isactive, name) values (true, '23.49 Производство на други керамични изделия, некласифицирани другаде');
insert into code (isactive, name) values (true, '23.51 Производство на цимент');
insert into code (isactive, name) values (true, '23.52 Производство на вар и гипс');
insert into code (isactive, name) values (true, '23.61 Производство на изделия от бетон за строителството');
insert into code (isactive, name) values (true, '23.62 Производство на изделия от гипс за строителството');
insert into code (isactive, name) values (true, '23.63 Производство на готови бетонови смеси');
insert into code (isactive, name) values (true, '23.64 Производство на неогнеупорни строителни разтвори');
insert into code (isactive, name) values (true, '23.65 Производство на влакнесто-циментови изделия');
insert into code (isactive, name) values (true, '23.69 Производство на други изделия от бетон, гипс и цимент');
insert into code (isactive, name) values (true, '23.70 Рязане, профилиране и обработване на строителни и декоративни скални материали');
insert into code (isactive, name) values (true, '23.91 Производство на абразивни изделия');
insert into code (isactive, name) values (true, '23.99 Производство на изделия от други неметални минерали, некласифицирани другаде');
insert into code (isactive, name) values (true, '24.10 Производство на чугун, стомана и феросплави');
insert into code (isactive, name) values (true, '24.20 Производство на тръби, кухи профили и фитинги за тях от стомана');
insert into code (isactive, name) values (true, '24.31 Студено изтегляне на пръти');
insert into code (isactive, name) values (true, '24.32 Студено валцуване на тесни ленти');
insert into code (isactive, name) values (true, '24.33 Студено формуване или прегъване на продукти от стомана');
insert into code (isactive, name) values (true, '24.34 Студено изтегляне на тел');
insert into code (isactive, name) values (true, '24.41 Производство на благородни метали');
insert into code (isactive, name) values (true, '24.42 Производство на алуминий');
insert into code (isactive, name) values (true, '24.43 Производство на олово, цинк, калай');
insert into code (isactive, name) values (true, '24.44 Производство на мед');
insert into code (isactive, name) values (true, '24.45 Производство на други цветни метали');
insert into code (isactive, name) values (true, '24.46 Преработка на ядрено гориво');
insert into code (isactive, name) values (true, '24.51 Леене на чугун');
insert into code (isactive, name) values (true, '24.52 Леене на стомана');
insert into code (isactive, name) values (true, '24.53 Леене на леки метали');
insert into code (isactive, name) values (true, '24.54 Леене на други метали');
insert into code (isactive, name) values (true, '25.11 Производство на метални конструкции и части от тях');
insert into code (isactive, name) values (true, '25.12 Производство на метална дограма');
insert into code (isactive, name) values (true, '25.21 Производство на котли за централно отопление и радиатори с неелектрическо загряване');
insert into code (isactive, name) values (true, '25.29 Производство на цистерни, резервоари и контейнери от метал');
insert into code (isactive, name) values (true, '25.30 Производство на парни котли, без котли за централно отопление');
insert into code (isactive, name) values (true, '25.40 Производство на въоръжение и боеприпаси');
insert into code (isactive, name) values (true, '25.50 Коване, щамповане и валцуване на метал; прахова металургия');
insert into code (isactive, name) values (true, '25.61 Повърхностно обработване и нанасяне на покритие върху метал');
insert into code (isactive, name) values (true, '25.62 Механично обработване на метал');
insert into code (isactive, name) values (true, '25.71 Производство на кухненски прибори и ножарски изделия');
insert into code (isactive, name) values (true, '25.72 Производство на строителен и мебелен обков');
insert into code (isactive, name) values (true, '25.73 Производство на сечива и инструменти за ръчна работа');
insert into code (isactive, name) values (true, '25.91 Производство на варели и подобни съдове от стомана');
insert into code (isactive, name) values (true, '25.92 Производство на леки опаковки от метал');
insert into code (isactive, name) values (true, '25.93 Производство на изделия от тел, вериги и пружини');
insert into code (isactive, name) values (true, '25.94 Производство на свързващи елементи');
insert into code (isactive, name) values (true, '25.99 Производство на други метални изделия, некласифицирани другаде');
insert into code (isactive, name) values (true, '26.11 Производство на електронни елементи');
insert into code (isactive, name) values (true, '26.12 Производство на монтирани печатни платки');
insert into code (isactive, name) values (true, '26.20 Производство на компютърна техника');
insert into code (isactive, name) values (true, '26.30 Производство на радио-, телевизионна и далекосъобщителна техника');
insert into code (isactive, name) values (true, '26.40 Производство на битова електроника');
insert into code (isactive, name) values (true, '26.51 Производство на уреди и апарати за измерване, изпитване и навигация');
insert into code (isactive, name) values (true, '26.52 Производство на часовници и часовникови механизми');
insert into code (isactive, name) values (true, '26.60 Производство на излъчващи електромедицински и терапевтични апарати');
insert into code (isactive, name) values (true, '26.70 Производство на оптични уреди и елементи и фотографска техника');
insert into code (isactive, name) values (true, '26.80 Производство на магнитни и оптични носители, незаписани');
insert into code (isactive, name) values (true, '27.11 Производство на електрически двигатели, генератори и трансформатори');
insert into code (isactive, name) values (true, '27.12 Производство на апарати за управление и разпределение на електрическа енергия');
insert into code (isactive, name) values (true, '27.20 Производство на акумулаторни батерии и акумулатори');
insert into code (isactive, name) values (true, '27.31 Производство на кабели от оптични влакна');
insert into code (isactive, name) values (true, '27.32 Производство на други електрически и електронни проводници и кабели');
insert into code (isactive, name) values (true, '27.33 Производство на електроинсталационни изделия');
insert into code (isactive, name) values (true, '27.40 Производство на лампи и осветители');
insert into code (isactive, name) values (true, '27.51 Производство на битови електроуреди');
insert into code (isactive, name) values (true, '27.52 Производство на неелектрически битови уреди');
insert into code (isactive, name) values (true, '27.90 Производство на други електрически съоръжения');
insert into code (isactive, name) values (true, '28.11 Производство на турбини и двигатели, без авиационни, автомобилни и мотоциклетни');
insert into code (isactive, name) values (true, '28.12 Производство на хидравлични помпи, хидравлични и пневматични двигатели');
insert into code (isactive, name) values (true, '28.13 Производство на други помпи и компресори');
insert into code (isactive, name) values (true, '28.14 Производство на арматурни изделия');
insert into code (isactive, name) values (true, '28.15 Производство на лагери, предавки и съединители');
insert into code (isactive, name) values (true, '28.21 Производство на пещи и горелки');
insert into code (isactive, name) values (true, '28.22 Производство на подемно-транспортни машини');
insert into code (isactive, name) values (true, '28.23 Производство на офис техника, без компютърната');
insert into code (isactive, name) values (true, '28.24 Производство на преносими инструменти с вграден двигател');
insert into code (isactive, name) values (true, '28.25 Производство на промишлено хладилно и вентилационно оборудване');
insert into code (isactive, name) values (true, '28.29 Производство на други машини с общо предназначение, некласифицирани другаде');
insert into code (isactive, name) values (true, '28.30 Производство на машини за селското и горското стопанство');
insert into code (isactive, name) values (true, '28.41 Производство на машини за обработка на метал');
insert into code (isactive, name) values (true, '28.49 Производство на други обработващи машини');
insert into code (isactive, name) values (true, '28.91 Производство на машини и оборудване за металургията и леярството');
insert into code (isactive, name) values (true, '28.92 Производство на машини за добива и строителството');
insert into code (isactive, name) values (true, '28.93 Производство на машини и оборудване за преработка на храни, напитки и тютюн');
insert into code (isactive, name) values (true, '28.94 Производство на машини за текстил, облекло, кожи и кожени изделия');
insert into code (isactive, name) values (true, '28.95 Производство на машини за хартия, картон и изделия от хартия и картон');
insert into code (isactive, name) values (true, '28.96 Производство на машини за каучук или пластмаси');
insert into code (isactive, name) values (true, '28.99 Производство на други машини със специално предназначение, некласифицирани другаде');
insert into code (isactive, name) values (true, '29.10 Производство на автомобили и техните двигатели');
insert into code (isactive, name) values (true, '29.20 Производство на купета и каросерии за автомобили; производство на ремаркета и полуремаркета');
insert into code (isactive, name) values (true, '29.31 Производство на електронни и електрически части и устройства за автомобили');
insert into code (isactive, name) values (true, '29.32 Производство на други части и принадлежности за автомобили');
insert into code (isactive, name) values (true, '30.11 Строителство на плавателни съдове, без тези за отдих');
insert into code (isactive, name) values (true, '30.12 Строителство на плавателни съдове за отдих');
insert into code (isactive, name) values (true, '30.20 Производство на локомотиви, мотриси и вагони');
insert into code (isactive, name) values (true, '30.30 Производство на въздухоплавателни и космически средства и техните двигатели');
insert into code (isactive, name) values (true, '30.40 Производство на бойни бронирани транспортни машини');
insert into code (isactive, name) values (true, '30.91 Производство на мотоциклети и техните двигатели');
insert into code (isactive, name) values (true, '30.92 Производство на велосипеди и инвалидни колички');
insert into code (isactive, name) values (true, '30.99 Производство на други превозни средства, некласифицирани другаде');
insert into code (isactive, name) values (true, '31.01 Производство на мебели за офиси и магазини');
insert into code (isactive, name) values (true, '31.02 Производство на кухненски мебели');
insert into code (isactive, name) values (true, '31.03 Производство на матраци и дюшеци');
insert into code (isactive, name) values (true, '31.09 Производство на други мебели');
insert into code (isactive, name) values (true, '32.11 Сечене на монети');
insert into code (isactive, name) values (true, '32.12 Производство на бижутерийни и подобни изделия от благородни метали');
insert into code (isactive, name) values (true, '32.13 Производство на бижута имитация');
insert into code (isactive, name) values (true, '32.20 Производство на музикални инструменти');
insert into code (isactive, name) values (true, '32.30 Производство на спортни стоки');
insert into code (isactive, name) values (true, '32.40 Производство на игри и детски играчки');
insert into code (isactive, name) values (true, '32.50 Производство на медицински и зъболекарски инструменти и средства');
insert into code (isactive, name) values (true, '32.91 Производство на метли и четки');
insert into code (isactive, name) values (true, '32.99 Други разнообразни производства, некласифицирани другаде');
insert into code (isactive, name) values (true, '33.11 Ремонт на метални изделия');
insert into code (isactive, name) values (true, '33.12 Ремонт на машини и оборудване, с общо и специално предназначение');
insert into code (isactive, name) values (true, '33.13 Ремонт на електронни и оптични уреди и апарати');
insert into code (isactive, name) values (true, '33.14 Ремонт на електрически съоръжения');
insert into code (isactive, name) values (true, '33.15 Ремонт и поддържане на плавателни съдове');
insert into code (isactive, name) values (true, '33.16 Ремонт и поддържане на въздухоплавателни и космически средства');
insert into code (isactive, name) values (true, '33.17 Ремонт и поддържане на други превозни средства');
insert into code (isactive, name) values (true, '33.19 Ремонт на друго оборудване');
insert into code (isactive, name) values (true, '33.20 Инсталиране на машини и оборудване');
insert into code (isactive, name) values (true, '35.11 Производство на електрическа енергия');
insert into code (isactive, name) values (true, '35.12 Пренос на електрическа енергия');
insert into code (isactive, name) values (true, '35.13 Разпределение на електрическа енергия');
insert into code (isactive, name) values (true, '35.14 Търговия с електрическа енергия');
insert into code (isactive, name) values (true, '35.21 Производство на газообразни горива');
insert into code (isactive, name) values (true, '35.22 Разпределение на газообразни горива по газоразпределителните мрежи');
insert into code (isactive, name) values (true, '35.23 Търговия с газообразни горива по газоразпределителните мрежи');
insert into code (isactive, name) values (true, '35.30 Производство и разпределение на топлинна енергия');
insert into code (isactive, name) values (true, '36.00 Събиране, пречистване и доставяне на води');
insert into code (isactive, name) values (true, '37.00 Събиране, отвеждане и пречистване на отпадъчни води');
insert into code (isactive, name) values (true, '38.11 Събиране на неопасни отпадъци');
insert into code (isactive, name) values (true, '38.12 Събиране на опасни отпадъци');
insert into code (isactive, name) values (true, '38.21 Обработване и обезвреждане на неопасни отпадъци');
insert into code (isactive, name) values (true, '38.22 Обработване и обезвреждане на опасни отпадъци');
insert into code (isactive, name) values (true, '38.31 Разкомплектоване на отпадъци');
insert into code (isactive, name) values (true, '38.32 Рециклиране на сортирани отпадъци');
insert into code (isactive, name) values (true, '39.00 Възстановяване и други услуги по управление на отпадъци');
insert into code (isactive, name) values (true, '41.10 Дейности по реализиране на инвестиционни проекти за сгради');
insert into code (isactive, name) values (true, '41.20 Строителство на жилищни и нежилищни сгради');
insert into code (isactive, name) values (true, '42.11 Строителство на автомагистрали, пътища и самолетни писти');
insert into code (isactive, name) values (true, '42.12 Строителство на подземни и надземни релсови пътища');
insert into code (isactive, name) values (true, '42.13 Строителство на мостове и тунели');
insert into code (isactive, name) values (true, '42.21 Строителство на преносни и разпределителни тръбопроводи');
insert into code (isactive, name) values (true, '42.22 Строителство на преносни и разпределителни електрически и далекосъобщителни мрежи');
insert into code (isactive, name) values (true, '42.91 Строителство на хидротехнически съоръжения');
insert into code (isactive, name) values (true, '42.99 Строителство на други съоръжения, некласифицирани другаде');
insert into code (isactive, name) values (true, '43.11 Събаряне и разрушаване');
insert into code (isactive, name) values (true, '43.12 Земни работи');
insert into code (isactive, name) values (true, '43.13 Сондиране и пробиване');
insert into code (isactive, name) values (true, '43.21 Изграждане на електрически инсталации');
insert into code (isactive, name) values (true, '43.22 Изграждане на водопроводни, канализационни, отоплителни и климатични инсталации');
insert into code (isactive, name) values (true, '43.29 Изграждане на други инсталации');
insert into code (isactive, name) values (true, '43.31 Полагане на мазилки');
insert into code (isactive, name) values (true, '43.32 Монтаж на дограма и дърводелски работи');
insert into code (isactive, name) values (true, '43.33 Полагане на облицовки и настилки');
insert into code (isactive, name) values (true, '43.34 Боядисване и стъклопоставяне');
insert into code (isactive, name) values (true, '43.39 Други довършителни строителни дейности');
insert into code (isactive, name) values (true, '43.91 Покривни работи');
insert into code (isactive, name) values (true, '43.99 Други специализирани строителни дейности, некласифицирани другаде');
insert into code (isactive, name) values (true, '45.11 Търговия с леки и лекотоварни автомобили до 3.5 т');
insert into code (isactive, name) values (true, '45.19 Търговия с други автомобили над 3.5 т');
insert into code (isactive, name) values (true, '45.20 Техническо обслужване и ремонт на автомобили');
insert into code (isactive, name) values (true, '45.31 Търговия на едро с части и принадлежности за автомобили');
insert into code (isactive, name) values (true, '45.32 Търговия на дребно с части и принадлежности за автомобили');
insert into code (isactive, name) values (true, '45.40 Търговия с мотоциклети и части за тях, техническо обслужване и ремонт на мотоциклети');
insert into code (isactive, name) values (true, '46.11 Търговско посредничество със селскостопански суровини, живи животни, текстилни суровини и полуфабрикати');
insert into code (isactive, name) values (true, '46.12 Търговско посредничество с горива, руди, метали и химични продукти');
insert into code (isactive, name) values (true, '46.13 Търговско посредничество с дървен материал и материали за строителството');
insert into code (isactive, name) values (true, '46.14 Търговско посредничество с машини, промишлено оборудване, кораби и самолети');
insert into code (isactive, name) values (true, '46.15 Търговско посредничество с мебели, стоки за бита, железария и метални изделия');
insert into code (isactive, name) values (true, '46.16 Търговско посредничество с текстил, облекло, обувки и кожени изделия');
insert into code (isactive, name) values (true, '46.17 Търговско посредничество с хранителни стоки, напитки и тютюневи изделия');
insert into code (isactive, name) values (true, '46.18 Специализирано търговско посредничество с други групи стоки');
insert into code (isactive, name) values (true, '46.19 Неспециализирано търговско посредничество с разнообразни стоки');
insert into code (isactive, name) values (true, '46.21 Търговия на едро със зърно, семена, фуражи и необработен тютюн');
insert into code (isactive, name) values (true, '46.22 Търговия на едро с цветя и растения');
insert into code (isactive, name) values (true, '46.23 Търговия на едро с живи животни');
insert into code (isactive, name) values (true, '46.24 Търговия на едро със сурови и обработени кожи');
insert into code (isactive, name) values (true, '46.31 Търговия на едро с плодове и зеленчуци');
insert into code (isactive, name) values (true, '46.32 Търговия на едро с месо и месни продукти');
insert into code (isactive, name) values (true, '46.33 Търговия на едро с мляко и млечни продукти, яйца, хранителни масла и мазнини');
insert into code (isactive, name) values (true, '46.34 Търговия на едро с напитки');
insert into code (isactive, name) values (true, '46.35 Търговия на едро с тютюневи изделия');
insert into code (isactive, name) values (true, '46.36 Търговия на едро със захар, захарни и шоколадови изделия');
insert into code (isactive, name) values (true, '46.37 Търговия на едро с кафе, чай, какао и подправки');
insert into code (isactive, name) values (true, '46.38 Специализирана търговия на едро с други хранителни стоки');
insert into code (isactive, name) values (true, '46.39 Неспециализирана търговия на едро с хранителни стоки, напитки и тютюневи изделия');
insert into code (isactive, name) values (true, '46.41 Търговия на едро с текстил и галантерийни стоки');
insert into code (isactive, name) values (true, '46.42 Търговия на едро с облекло и обувки');
insert into code (isactive, name) values (true, '46.43 Търговия на едро с битова електроника и електроуреди');
insert into code (isactive, name) values (true, '46.44 Търговия на едро с порцеланови и стъкларски изделия и почистващи препарати');
insert into code (isactive, name) values (true, '46.45 Търговия на едро с парфюмерийни и козметични стоки');
insert into code (isactive, name) values (true, '46.46 Търговия на едро с фармацевтични стоки, медицинска техника и апаратура');
insert into code (isactive, name) values (true, '46.47 Търговия на едро с мебели, килими и осветители');
insert into code (isactive, name) values (true, '46.48 Търговия на едро с часовници и бижутерия');
insert into code (isactive, name) values (true, '46.49 Търговия на едро с други нехранителни потребителски стоки');
insert into code (isactive, name) values (true, '46.51 Търговия на едро с компютри, периферни устройства за тях и програмни продукти');
insert into code (isactive, name) values (true, '46.52 Търговия на едро с електронни елементи и комуникационна техника');
insert into code (isactive, name) values (true, '46.61 Търговия на едро с машини и оборудване за селското и горското стопанство и части за тях');
insert into code (isactive, name) values (true, '46.62 Търговия на едро с обработващи машини и части за тях');
insert into code (isactive, name) values (true, '46.63 Търговия на едро с машини и оборудване за добива и строителството и части за тях');
insert into code (isactive, name) values (true, '46.64 Търговия на едро с машини за производство на текстил, облекло и кожени изделия и части за тях');
insert into code (isactive, name) values (true, '46.65 Търговия на едро с офис мебели');
insert into code (isactive, name) values (true, '46.66 Търговия на едро с друга офис техника, без компютри');
insert into code (isactive, name) values (true, '46.69 Търговия на едро с други машини и оборудване със стопанско предназначение, некласифицирана другаде, и части за тях');
insert into code (isactive, name) values (true, '46.71 Търговия на едро с твърди, течни и газообразни горива и подобни продукти');
insert into code (isactive, name) values (true, '46.72 Търговия на едро с метали и руди');
insert into code (isactive, name) values (true, '46.73 Търговия на едро с дървен материал, материали за строителството и санитарно оборудване');
insert into code (isactive, name) values (true, '46.74 Търговия на едро с железария и арматурни изделия');
insert into code (isactive, name) values (true, '46.75 Търговия на едро с химични вещества и продукти');
insert into code (isactive, name) values (true, '46.76 Специализирана търговия на едро с други междинни продукти');
insert into code (isactive, name) values (true, '46.77 Търговия на едро с отпадъци и скрап');
insert into code (isactive, name) values (true, '46.90 Неспециализирана търговия на едро');
insert into code (isactive, name) values (true, '47.11 Търговия на дребно в неспециализирани магазини предимно с хранителни стоки, напитки и тютюневи изделия');
insert into code (isactive, name) values (true, '47.19 Търговия на дребно в неспециализирани магазини с разнообразни стоки');
insert into code (isactive, name) values (true, '47.21 Търговия на дребно с плодове и зеленчуци');
insert into code (isactive, name) values (true, '47.22 Търговия на дребно с месо и месни продукти');
insert into code (isactive, name) values (true, '47.23 Търговия на дребно с риба и други морски храни');
insert into code (isactive, name) values (true, '47.24 Търговия на дребно с хляб, хлебни, захарни и сладкарски изделия');
insert into code (isactive, name) values (true, '47.25 Търговия на дребно с напитки');
insert into code (isactive, name) values (true, '47.26 Търговия на дребно с тютюневи изделия');
insert into code (isactive, name) values (true, '47.29 Търговия на дребно с други хранителни стоки');
insert into code (isactive, name) values (true, '47.30 Търговия на дребно с автомобилни горива и смазочни материали');
insert into code (isactive, name) values (true, '47.41 Търговия на дребно с компютри, периферни устройства за тях и програмни продукти');
insert into code (isactive, name) values (true, '47.42 Търговия на дребно с телефонни апарати и други устройства за далекосъобщения');
insert into code (isactive, name) values (true, '47.43 Търговия на дребно с битова електроника');
insert into code (isactive, name) values (true, '47.51 Търговия на дребно с текстил и галантерийни стоки');
insert into code (isactive, name) values (true, '47.52 Търговия на дребно с железария, бои и плоско стъкло');
insert into code (isactive, name) values (true, '47.53 Търговия на дребно с тапети, килими и други стенни и подови покрития');
insert into code (isactive, name) values (true, '47.54 Търговия на дребно с битови електроуреди');
insert into code (isactive, name) values (true, '47.59 Търговия на дребно с мебели, осветители и други стоки за бита, некласифицирани другаде');
insert into code (isactive, name) values (true, '47.61 Търговия на дребно с книги');
insert into code (isactive, name) values (true, '47.62 Търговия на дребно с вестници и канцеларски стоки');
insert into code (isactive, name) values (true, '47.63 Търговия на дребно с аудио- и видеозаписи');
insert into code (isactive, name) values (true, '47.64 Търговия на дребно със спортни стоки');
insert into code (isactive, name) values (true, '47.65 Търговия на дребно с игри и играчки');
insert into code (isactive, name) values (true, '47.71 Търговия на дребно с облекло');
insert into code (isactive, name) values (true, '47.72 Търговия на дребно с обувки и кожени изделия');
insert into code (isactive, name) values (true, '47.73 Търговия на дребно с лекарства и други фармацевтични стоки');
insert into code (isactive, name) values (true, '47.74 Търговия на дребно с медицински и ортопедични стоки');
insert into code (isactive, name) values (true, '47.75 Търговия на дребно с парфюмерийни и козметични стоки и тоалетни принадлежности');
insert into code (isactive, name) values (true, '47.76 Търговия на дребно с цветя, растения, семена, торове, домашни любимци и храни за тях');
insert into code (isactive, name) values (true, '47.77 Търговия на дребно с часовници и бижутерия');
insert into code (isactive, name) values (true, '47.78 Търговия на дребно с други нехранителни стоки, некласифицирана другаде');
insert into code (isactive, name) values (true, '47.79 Търговия на дребно в магазини с употребявани стоки');
insert into code (isactive, name) values (true, '47.81 Търговия на дребно на открити щандове и пазари с хранителни стоки, напитки и тютюневи изделия');
insert into code (isactive, name) values (true, '47.82 Търговия на дребно на открити щандове и пазари с текстил, облекло и обувки');
insert into code (isactive, name) values (true, '47.89 Търговия на дребно на открити щандове и пазари с други стоки');
insert into code (isactive, name) values (true, '47.91 Търговия на дребно чрез поръчки по пощата, телефона или Интернет');
insert into code (isactive, name) values (true, '47.99 Търговия на дребно извън търговски обекти, некласифицирана другаде');
insert into code (isactive, name) values (true, '49.10 Пътнически железопътен транспорт, междуселищен');
insert into code (isactive, name) values (true, '49.20 Товарен железопътен транспорт');
insert into code (isactive, name) values (true, '49.31 Пътнически градски и крайградски транспорт');
insert into code (isactive, name) values (true, '49.32 Пътнически таксиметров транспорт');
insert into code (isactive, name) values (true, '49.39 Друг пътнически сухопътен транспорт, некласифициран другаде');
insert into code (isactive, name) values (true, '49.41 Товарен автомобилен транспорт');
insert into code (isactive, name) values (true, '49.42 Услуги по преместване');
insert into code (isactive, name) values (true, '49.50 Тръбопроводен транспорт');
insert into code (isactive, name) values (true, '50.10 Пътнически морски и крайбрежен транспорт');
insert into code (isactive, name) values (true, '50.20 Товарен морски и крайбрежен транспорт');
insert into code (isactive, name) values (true, '50.30 Пътнически транспорт по вътрешни водни пътища');
insert into code (isactive, name) values (true, '50.40 Товарен транспорт по вътрешни водни пътища');
insert into code (isactive, name) values (true, '51.10 Пътнически въздушен транспорт');
insert into code (isactive, name) values (true, '51.21 Товарен въздушен транспорт');
insert into code (isactive, name) values (true, '51.22 Космически транспорт');
insert into code (isactive, name) values (true, '52.10 Складиране и съхраняване на товари');
insert into code (isactive, name) values (true, '52.21 Експлоатация на инфраструктурата в сухопътния транспорт');
insert into code (isactive, name) values (true, '52.22 Спомагателни дейности във водния транспорт');
insert into code (isactive, name) values (true, '52.23 Спомагателни дейности във въздушния транспорт');
insert into code (isactive, name) values (true, '52.24 Обработка на товари');
insert into code (isactive, name) values (true, '52.29 Други спомагателни дейности в транспорта');
insert into code (isactive, name) values (true, '53.10 Дейност на пощи, предоставящи универсална пощенска услуга');
insert into code (isactive, name) values (true, '53.20 Други пощенски и куриерски дейности');
insert into code (isactive, name) values (true, '55.10 Хотели и подобни места за настаняване');
insert into code (isactive, name) values (true, '55.20 Туристическо и друго краткосрочно настаняване');
insert into code (isactive, name) values (true, '55.30 Къмпинги и терени за каравани и къмпинг–автомобили');
insert into code (isactive, name) values (true, '55.90 Други места за настаняване');
insert into code (isactive, name) values (true, '56.10 Дейност на ресторанти и заведения за бързо обслужване');
insert into code (isactive, name) values (true, '56.21 Приготвяне и доставяне на храна по конкретен повод');
insert into code (isactive, name) values (true, '56.29 Други дейности по приготвяне и доставяне на храна');
insert into code (isactive, name) values (true, '56.30 Дейност на питейни заведения');
insert into code (isactive, name) values (true, '58.11 Издаване на книги');
insert into code (isactive, name) values (true, '58.12 Издаване на указатели, справочници и адресни списъци');
insert into code (isactive, name) values (true, '58.13 Издаване на вестници');
insert into code (isactive, name) values (true, '58.14 Издаване на списания и други периодични издания');
insert into code (isactive, name) values (true, '58.19 Друга издателска дейност');
insert into code (isactive, name) values (true, '58.21 Издаване на компютърни игри');
insert into code (isactive, name) values (true, '58.29 Издаване на други програмни продукти');
insert into code (isactive, name) values (true, '59.11 Производство на филми и телевизионни предавания');
insert into code (isactive, name) values (true, '59.12 Технически дейности, свързани с производство на филми и телевизионни предавания (постпродукция)');
insert into code (isactive, name) values (true, '59.13 Разпространение на филми и телевизионни предавания');
insert into code (isactive, name) values (true, '59.14 Прожектиране на филми');
insert into code (isactive, name) values (true, '59.20 Звукозаписване и издаване на музика');
insert into code (isactive, name) values (true, '60.10 Създаване и излъчване на радиопрограми');
insert into code (isactive, name) values (true, '60.20 Създаване и излъчване на телевизионни програми');
insert into code (isactive, name) values (true, '61.10 Далекосъобщителна дейност чрез фиксирани мрежи');
insert into code (isactive, name) values (true, '61.20 Далекосъобщителна дейност по безжичен път');
insert into code (isactive, name) values (true, '61.30 Спътникова далекосъобщителна дейност');
insert into code (isactive, name) values (true, '61.90 Други далекосъобщителни дейности');
insert into code (isactive, name) values (true, '62.01 Компютърно програмиране');
insert into code (isactive, name) values (true, '62.02 Консултантска дейност по информационни технологии');
insert into code (isactive, name) values (true, '62.03 Управление и обслужване на компютърни средства и системи');
insert into code (isactive, name) values (true, '62.09 Други дейности в областта на информационните технологии');
insert into code (isactive, name) values (true, '63.11 Обработка на данни, хостинг и подобни дейности');
insert into code (isactive, name) values (true, '63.12 Web-портали');
insert into code (isactive, name) values (true, '63.91 Дейност на информационни агенции');
insert into code (isactive, name) values (true, '63.99 Други информационни услуги, некласифицирани другаде');
insert into code (isactive, name) values (true, '64.11 Дейност на централната банка');
insert into code (isactive, name) values (true, '64.19 Друго парично посредничество');
insert into code (isactive, name) values (true, '64.20 Дейност на холдингови дружества');
insert into code (isactive, name) values (true, '64.30 Фондове за инвестиране и подобни финансови субекти');
insert into code (isactive, name) values (true, '64.91 Финансов лизинг');
insert into code (isactive, name) values (true, '64.92 Други форми на предоставяне на кредит');
insert into code (isactive, name) values (true, '64.99 Предоставяне на други финансови услуги, без застраховане и допълнително пенсионно осигуряване, некласифицирани другаде');
insert into code (isactive, name) values (true, '65.11 Животозастраховане');
insert into code (isactive, name) values (true, '65.12 Друго застраховане, без животозастраховане');
insert into code (isactive, name) values (true, '65.20 Презастраховане');
insert into code (isactive, name) values (true, '65.30 Допълнително пенсионно осигуряване');
insert into code (isactive, name) values (true, '66.11 Управление на финансови пазари');
insert into code (isactive, name) values (true, '66.12 Посредническа дейност по сделки с ценни книжа и стоки');
insert into code (isactive, name) values (true, '66.19 Други спомагателни дейности във финансовите услуги, без застраховане и допълнително пенсионно осигуряване');
insert into code (isactive, name) values (true, '66.21 Оценяване на застрахователни рискове и щети');
insert into code (isactive, name) values (true, '66.22 Дейности на застрахователни брокери и агенти');
insert into code (isactive, name) values (true, '66.29 Други спомагателни дейности в застраховането и допълнителното пенсионно осигуряване');
insert into code (isactive, name) values (true, '66.30 Управление на фондове');
insert into code (isactive, name) values (true, '68.10 Покупка и продажба на собствени недвижими имоти');
insert into code (isactive, name) values (true, '68.20 Даване под наем и експлоатация на собствени недвижими имоти');
insert into code (isactive, name) values (true, '68.31 Дейност на агенции за недвижими имоти');
insert into code (isactive, name) values (true, '68.32 Управление на недвижими имоти');
insert into code (isactive, name) values (true, '69.10 Юридически дейности');
insert into code (isactive, name) values (true, '69.20 Счетоводни и одиторски дейности; данъчни консултации');
insert into code (isactive, name) values (true, '70.10 Дейност на централни офиси');
insert into code (isactive, name) values (true, '70.21 Консултантска дейност по връзки с обществеността');
insert into code (isactive, name) values (true, '70.22 Консултантска дейност по стопанско и друго управление');
insert into code (isactive, name) values (true, '71.11 Архитектурни дейности');
insert into code (isactive, name) values (true, '71.12 Инженерни дейности и технически консултации');
insert into code (isactive, name) values (true, '71.20 Технически изпитвания и анализи');
insert into code (isactive, name) values (true, '72.11 Научноизследователска и развойна дейност в областта на биотехнологиите');
insert into code (isactive, name) values (true, '72.19 Научноизследователска и развойна дейност в областта на естествените, медицинските, селскостопанските и техническите науки, без биотехнологиите');
insert into code (isactive, name) values (true, '72.20 Научноизследователска и развойна дейност в областта на обществените и хуманитарните науки');
insert into code (isactive, name) values (true, '73.11 Дейност на рекламни агенции');
insert into code (isactive, name) values (true, '73.12 Дейности по продажба на медийно време и място за реклама');
insert into code (isactive, name) values (true, '73.20 Проучване на пазари и изследване на общественото мнение');
insert into code (isactive, name) values (true, '74.10 Специализирани дейности в областта на дизайна');
insert into code (isactive, name) values (true, '74.20 Дейности в областта на фотографията');
insert into code (isactive, name) values (true, '74.30 Преводаческа дейност');
insert into code (isactive, name) values (true, '74.90 Други професионални дейности, некласифицирани другаде');
insert into code (isactive, name) values (true, '75.00 Ветеринарномедицинска дейност');
insert into code (isactive, name) values (true, '77.11 Даване под наем и оперативен лизинг на леки и лекотоварни автомобили, без водач');
insert into code (isactive, name) values (true, '77.12 Даване под наем и оперативен лизинг на тежкотоварни автомобили, без водач');
insert into code (isactive, name) values (true, '77.21 Даване под наем и оперативен лизинг на оборудване и екипировка за спорт и развлечения');
insert into code (isactive, name) values (true, '77.22 Даване под наем на видеокасети и дискове');
insert into code (isactive, name) values (true, '77.29 Даване под наем и оперативен лизинг на други лични и домакински вещи');
insert into code (isactive, name) values (true, '77.31 Даване под наем и оперативен лизинг на машини и оборудване за селското и горското стопанство, без оператор');
insert into code (isactive, name) values (true, '77.32 Даване под наем и оперативен лизинг на машини и оборудване за строителството, без оператор');
insert into code (isactive, name) values (true, '77.33 Даване под наем и оперативен лизинг на офис мебели и техника (вкл. компютри), без оператор');
insert into code (isactive, name) values (true, '77.34 Даване под наем и оперативен лизинг на плавателни съдове, без екипаж');
insert into code (isactive, name) values (true, '77.35 Даване под наем и оперативен лизинг на въздухоплавателни средства, без екипаж');
insert into code (isactive, name) values (true, '77.39 Даване под наем и оперативен лизинг на други машини и оборудване със стопанско предназначение, некласифицирани другаде');
insert into code (isactive, name) values (true, '77.40 Оперативен лизинг на интелектуална собственост и сходни продукти, без обектите на авторско право');
insert into code (isactive, name) values (true, '78.10 Посредническа дейност на агенции по наемане на работа');
insert into code (isactive, name) values (true, '78.20 Предоставяне на работна сила за временна заетост');
insert into code (isactive, name) values (true, '78.30 Други дейности по предоставяне на работна сила');
insert into code (isactive, name) values (true, '79.11 Туристическа агентска дейност');
insert into code (isactive, name) values (true, '79.12 Туроператорска дейност');
insert into code (isactive, name) values (true, '79.90 Други дейности, свързани с пътувания и резервации');
insert into code (isactive, name) values (true, '80.10 Частна охранителна дейност, без използване на технически системи за сигурност');
insert into code (isactive, name) values (true, '80.20 Дейности в областта на технически системи за сигурност');
insert into code (isactive, name) values (true, '80.30 Дейности по разследване и издирване');
insert into code (isactive, name) values (true, '81.10 Комплексно обслужване на сгради');
insert into code (isactive, name) values (true, '81.21 Неспециализирано вътрешно почистване на сгради');
insert into code (isactive, name) values (true, '81.22 Специализирано почистване на сгради и промишлени обекти');
insert into code (isactive, name) values (true, '81.29 Други дейности по почистване');
insert into code (isactive, name) values (true, '81.30 Оформяне и поддържане на озеленени площи');
insert into code (isactive, name) values (true, '82.11 Комбинирани административни офис дейности');
insert into code (isactive, name) values (true, '82.19 Размножаване, изготвяне на документи и други специализирани помощни офис дейности');
insert into code (isactive, name) values (true, '82.20 Дейност на телефонни центрове за услуги');
insert into code (isactive, name) values (true, '82.30 Организиране на конгреси и търговски изложения');
insert into code (isactive, name) values (true, '82.91 Дейности по събиране на парични вземания и на финансова информация');
insert into code (isactive, name) values (true, '82.92 Дейности по опаковане и пакетиране');
insert into code (isactive, name) values (true, '82.99 Друго спомагателно обслужване на стопанската дейност, некласифицирано другаде');
insert into code (isactive, name) values (true, '84.11 Общофункционално управление на държавата на централно и местно равнище');
insert into code (isactive, name) values (true, '84.12 Държавно управление в областта на здравеопазването, образованието и други социални дейности');
insert into code (isactive, name) values (true, '84.13 Държавно управление в областта на стопанската дейност');
insert into code (isactive, name) values (true, '84.21 Външни работи');
insert into code (isactive, name) values (true, '84.22 Отбрана');
insert into code (isactive, name) values (true, '84.23 Правосъдие');
insert into code (isactive, name) values (true, '84.24 Обществен ред и сигурност');
insert into code (isactive, name) values (true, '84.25 Пожарна безопасност и защита при бедствия');
insert into code (isactive, name) values (true, '84.30 Държавно обществено осигуряване');
insert into code (isactive, name) values (true, '85.10 Предучилищно образование');
insert into code (isactive, name) values (true, '85.20 Начално образование (първи етап на основното образование)');
insert into code (isactive, name) values (true, '85.31 Прогимназиално и средно общо образование');
insert into code (isactive, name) values (true, '85.32 Прогимназиално и средно професионално образование и обучение');
insert into code (isactive, name) values (true, '85.41 Професионално обучение след средно образование, но не висше');
insert into code (isactive, name) values (true, '85.42 Висше образование');
insert into code (isactive, name) values (true, '85.51 Неформално обучение в областта на спорта и активния отдих');
insert into code (isactive, name) values (true, '85.52 Неформално обучение в областта на културата');
insert into code (isactive, name) values (true, '85.53 Обучение на водачи на превозни средства');
insert into code (isactive, name) values (true, '85.59 Други образователни дейности, некласифицирани другаде');
insert into code (isactive, name) values (true, '85.60 Спомагателни дейности в областта на образованието');
insert into code (isactive, name) values (true, '86.10 Дейност на болници');
insert into code (isactive, name) values (true, '86.21 Дейност на общопрактикуващи лекари');
insert into code (isactive, name) values (true, '86.22 Дейност на лекари специалисти');
insert into code (isactive, name) values (true, '86.23 Дейност на лекари по дентална медицина');
insert into code (isactive, name) values (true, '86.90 Други дейности по хуманно здравеопазване');
insert into code (isactive, name) values (true, '87.10 Дейност на заведения със здравни грижи');
insert into code (isactive, name) values (true, '87.20 Социални грижи с настаняване за лица с умствена изостаналост, психичноболни и зависими от наркотици');
insert into code (isactive, name) values (true, '87.30 Социални грижи с настаняване за възрастни лица и хора с физически увреждания');
insert into code (isactive, name) values (true, '87.90 Други социални грижи с настаняване');
insert into code (isactive, name) values (true, '88.10 Социална работа без настаняване за възрастни лица и хора с увреждания');
insert into code (isactive, name) values (true, '88.91 Дневни грижи за малки деца');
insert into code (isactive, name) values (true, '88.99 Друга социална работа без настаняване, некласифицирана другаде');
insert into code (isactive, name) values (true, '90.01 Изпълнителско изкуство');
insert into code (isactive, name) values (true, '90.02 Спомагателни дейности, свързани с изпълнителско изкуство');
insert into code (isactive, name) values (true, '90.03 Творческа дейност в областта на литературата и изкуствата');
insert into code (isactive, name) values (true, '90.04 Експлоатация на зали за представления');
insert into code (isactive, name) values (true, '91.01 Дейност на библиотеки и архиви');
insert into code (isactive, name) values (true, '91.02 Дейност на музеи');
insert into code (isactive, name) values (true, '91.03 Опазване и стопанисване на културно-исторически паметници и места');
insert into code (isactive, name) values (true, '91.04 Дейност на ботанически и зоологически градини, природни паркове и резервати');
insert into code (isactive, name) values (true, '92.00 Организиране на хазартни игри');
insert into code (isactive, name) values (true, '93.11 Експлоатация на спортни обекти и съоръжения');
insert into code (isactive, name) values (true, '93.12 Дейност на спортни клубове');
insert into code (isactive, name) values (true, '93.13 Дейност на фитнес центрове и зали');
insert into code (isactive, name) values (true, '93.19 Други дейности в областта на спорта');
insert into code (isactive, name) values (true, '93.21 Дейност на увеселителни и тематични паркове');
insert into code (isactive, name) values (true, '93.29 Други дейности, свързани с развлечения и отдих');
insert into code (isactive, name) values (true, '94.11 Дейност на бизнес организации и организации на работодатели');
insert into code (isactive, name) values (true, '94.12 Дейност на професионални организации');
insert into code (isactive, name) values (true, '94.20 Дейност на синдикални организации');
insert into code (isactive, name) values (true, '94.91 Дейност на религиозни организации');
insert into code (isactive, name) values (true, '94.92 Дейност на политически организации');
insert into code (isactive, name) values (true, '94.99 Дейност на други организации с нестопанска цел, некласифицирани другаде');
insert into code (isactive, name) values (true, '95.11 Ремонт на компютри и периферни устройства за тях');
insert into code (isactive, name) values (true, '95.12 Ремонт на телефонни апарати и други устройства за далекосъобщения');
insert into code (isactive, name) values (true, '95.21 Ремонт на битова електроника');
insert into code (isactive, name) values (true, '95.22 Ремонт на битови електроуреди и друго оборудване за дома и градината');
insert into code (isactive, name) values (true, '95.23 Поправка на обувки и кожени изделия');
insert into code (isactive, name) values (true, '95.24 Ремонт на мебели и предмети за обзавеждане');
insert into code (isactive, name) values (true, '95.25 Ремонт на часовници и бижута');
insert into code (isactive, name) values (true, '95.29 Ремонт на други лични и домакински вещи');
insert into code (isactive, name) values (true, '96.01 Пране и химическо чистене');
insert into code (isactive, name) values (true, '96.02 Фризьорски и козметични услуги');
insert into code (isactive, name) values (true, '96.03 Организиране на погребения и свързани с тях услуги');
insert into code (isactive, name) values (true, '96.04 Поддържане на добро физическо състояние');
insert into code (isactive, name) values (true, '96.09 Други персонални услуги, некласифицирани другаде');
insert into code (isactive, name) values (true, '97.00 Дейности на домакинства като работодатели на домашен персонал');
insert into code (isactive, name) values (true, '98.10 Недиференцирани дейности на домакинства по производство на стоки за собствено потребление');
insert into code (isactive, name) values (true, '98.20 Недиференцирани дейности на домакинства по производство на услуги за собствено потребление');
insert into code (isactive, name) values (true, '99.00 Дейности на екстериториални организации и служби');