insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('МОСВ','MOEW','mosv',3,1,true,0,24);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('ИОСВ',null,null,5,2,true,0,null);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - София','RIEW - Sofia',null,1,3,true,0,13);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Благоевград','RIEW - Blagoevgrad',null,1,4,true,0,1);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Бургас','RIEW - Burgas',null,1,5,true,0,2);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Варна','RIEW - Varna',null,1,6,true,0,3);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Велико Търново','Veliko Tarnovo - Sofia',null,1,7,true,0,4);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Враца','RIEW - Vratsa',null,1,8,true,0,5);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Монтана','RIEW - Montana',null,1,9,true,0,6);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Пазарджик','RIEW - Pazardzhik',null,1,10,true,0,7);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Перник','RIEW - Pernik',null,1,11,true,0,8);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Плевен','RIEW - Pleven',null,1,12,true,0,9);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Пловдив','RIEW - Plovdiv',null,1,13,true,0,10);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Русе','RIEW - Ruse',null,1,14,true,0,11);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Стара Загора','RIEW - Stara Zagora',null,1,15,true,0,14);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Смолян','RIEW - Smolyan',null,1,16,true,0,12);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Хасково','RIEW - Haskovo',null,1,17,true,0,15);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Шумен','RIEW - Shumen',null,1,18,true,0,16);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('РИОСВ - Всички','RIEW - All',null,1,19,true,0,17);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('БД - Дунавски район','RBD - Dunav region',null,2,20,true,0,21);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('БД - Западнобеломорски район','RBD - East Aegean River region',null,2,21,true,0,18);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('БД - Източнобеломорски район','RBD - West Aegean River region',null,2,22,true,0,20);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('БД - Черноморски район','RBD - Black sea region',null,2,23,true,0,19);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('БД - Всички','RBD - All',null,2,24,true,0,22);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('ДНП - Пирин','DNP - Pirin',null,4,25,true,0,null);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('ДНП - Рила','DNP - Rila',null,4,26,true,0,null);
insert into authority(name, namealt, alias, authoritytype, vieworder, isactive, version, migrationid) values('ДНП - Централен балкан','DNP - Central balkan',null,4,27,true,0,null);
