insert into prosecutor (prosecutortype, isactive, name, vieworder) values (1, true, 'Национална Следствена Служба', 1);

insert into prosecutor (prosecutortype, isactive, name, vieworder) values (2, true, 'Апелативна прокуратура - Бургас', 2);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (2, true, 'Апелативна прокуратура - Варна', 3);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (2, true, 'Апелативна прокуратура - Велико Търново', 4);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (2, true, 'Апелативна прокуратура - Пловдив', 5);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (2, true, 'Апелативна прокуратура - София', 6);

insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Благоевград', 7);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Бургас', 8);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Варна', 9);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Велико Търново', 10);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Видин', 11);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Враца', 12);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Габрово', 13);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Добрич', 14);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Кърджали', 15);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Кюстендил', 16);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Ловеч', 17);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Монтана', 18);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Пазарджик', 19);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Перник', 20);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Плевен', 21);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Пловдив', 22);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Разград', 23);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Русе', 24);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Силистра', 25);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Сливен', 26);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Смолян', 27);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - София', 28);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Стара Загора', 29);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Търговище', 30);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Хасково', 31);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Шумен', 32);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Окръжна прокуратура - Ямбол', 33);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (3, true, 'Софийска градска прокуратура', 34);

insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Благоевград', 35);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Бургас', 36);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Варна', 37);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Велико Търново', 38);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Видин', 39);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Враца', 40);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Габрово', 41);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Добрич', 42);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Елин Пелин', 43);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Костинброд', 44);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Кърджали', 45);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Кюстендил', 46);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Ловеч', 47);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Монтана', 48);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Пазарджик', 49);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Перник', 50);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Плевен', 51);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Пловдив', 52);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Разград', 53);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Русе', 54);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Самоков', 55);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Силистра', 56);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Сливен', 57);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Смолян', 58);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Стара Загора', 59);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Търговище', 60);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Хасково', 61);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Шумен', 62);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Районна прокуратура - Ямбол', 63);
insert into prosecutor (prosecutortype, isactive, name, vieworder) values (4, true, 'Софийска районна прокуратура', 64);